accounts:
  - name: alice
    coins: ["20000token", "200000000stake", "50000000000mitocell"]
  - name: bob
    coins: ["10000token", "100000000stake", "50000000000mitocell"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  # To generate ts-client 
  # typescript:
  #   path: "ts-client"
  # 
  # To generate vue files
  # vuex:
  #   path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake", "100000mitocell"]
